<?php

return [
    'challenge_year' => (int) env('EXOPLANET_CHALLENGE_YEAR', 2026),
    'team_code_prefix' => env('EXOPLANET_TEAM_CODE_PREFIX', 'EXP'),
    'submission_code_prefix' => env('EXOPLANET_SUBMISSION_CODE_PREFIX', 'SUB'),
    'presign_minutes' => (int) env('EXOPLANET_PRESIGN_MINUTES', 15),
    'download_seconds' => (int) env('EXOPLANET_DOWNLOAD_SECONDS', 60),
    'multipart_threshold' => (int) env('EXOPLANET_MULTIPART_THRESHOLD', 8_388_608),
    'part_size_bytes' => (int) env('EXOPLANET_PART_SIZE_BYTES', 8_388_608),
    'settings_id' => '00000000-0000-0000-0000-000000000001',
    'frontend_url' => env('FRONTEND_URL', 'http://localhost:5173'),
    'seed_admin_email' => env('SEED_ADMIN_EMAIL', 'admin@localhost'),
    'seed_admin_password' => env('SEED_ADMIN_PASSWORD'),
    'activation_ttl_hours' => 24,
    'invitation_ttl_days' => 7,
    'password_reset_ttl_hours' => 1,
    'file_policy' => [
        'maxBytesByType' => [
            'report_pdf' => 20 * 1024 * 1024,
            'notebook' => 20 * 1024 * 1024,
            'archive_zip' => 500 * 1024 * 1024,
            'presentation' => 50 * 1024 * 1024,
            'readme' => 2 * 1024 * 1024,
            'visualization' => 10 * 1024 * 1024,
            'dataset_csv' => 20 * 1024 * 1024,
            'other' => 20 * 1024 * 1024,
        ],
        'allowedExtensionsByType' => [
            'report_pdf' => ['pdf'],
            'notebook' => ['ipynb'],
            'archive_zip' => ['zip'],
            'presentation' => ['pptx', 'ppt'],
            'readme' => ['md'],
            'visualization' => ['png', 'jpg', 'jpeg'],
            'dataset_csv' => ['csv'],
            'other' => ['pdf', 'ipynb', 'zip', 'pptx', 'ppt', 'md', 'png', 'jpg', 'jpeg', 'csv'],
        ],
        'allowedMimesByType' => [
            'report_pdf' => ['application/pdf'],
            'notebook' => ['application/json', 'application/x-ipynb+json'],
            'archive_zip' => ['application/zip', 'application/x-zip-compressed'],
            'presentation' => [
                'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'application/vnd.ms-powerpoint',
            ],
            'readme' => ['text/markdown', 'text/plain'],
            'visualization' => ['image/png', 'image/jpeg'],
            'dataset_csv' => ['text/csv', 'text/plain'],
            'other' => [
                'application/pdf',
                'application/json',
                'application/zip',
                'text/markdown',
                'text/plain',
                'image/png',
                'image/jpeg',
                'text/csv',
            ],
        ],
    ],
];
